### ISSUE TITLE
YAMLParseError

### ISSUE THREAD

**Issue by exuan** [Dunqing/resume#2]
```
YAMLParseError: Implicit map keys need to be followed by map values at line 3, column 1:
``` 
在使用 https://resume.todev.cc/ 编辑简历的时候， 编辑出 不符合解析的内容， 如 `print: true` 变成 `print:true`，
导致YAMLParseError，只能删掉MARKDOWN_RESUME_KEY或者覆盖MARKDOWN_RESUME_KEY里内容.

**Comment by Dunqing** [comment]
确实存在
